name: build & test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_USER: test
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Build
        env:
          DATABASE_URL: "postgresql://test:test@localhost:5432/test_db"
        run: cargo build --verbose
      - name: Run tests
        env:
          DATABASE_URL: "postgresql://test:test@localhost:5432/test_db"
        run: cargo test --verbose
